version: '3.8'

services:
  btc_address_dormant:
    build:
      context: .  # Pastikan konteks menunjuk ke direktori saat ini
      dockerfile: Dockerfile
    container_name: btc_address_dormant
    deploy:
      resources:
        limits:
          cpus: '15.0'
    volumes:
      - ./dormant.txt:/app/dormant.txt
    restart: always  # Tambahkan restart policy untuk stabilitas
    environment:
      - PYTHONUNBUFFERED=1  # Opsional: untuk output log yang lebih jelas
    entrypoint: ["python", "scanner.py"]  # Menetapkan ulang entrypoint jika perlu
