services:
  btc_address_dormant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc_address_dormant
    deploy:
      resources:
        limits:
          cpus: '15.0'
    volumes:
      - ./dormant.txt:/app/dormant.txt
    command: python scanner.py