services:
  btc_scanner:
    build:
      context: .  # Gunakan Dockerfile yang ada di direktori saat ini
    container_name: btc_scanner_dormant
    volumes:
      - ./data:/app/data  # Mount folder data di host ke /app/data di dalam container
    deploy:
      resources:
        limits:
          cpus: '15.0'  # Alokasikan 15 core CPU
    command: bash -c "python3 scanning.py"
